### ISSUE TITLE
README.md中的网络地址写错？

### ISSUE THREAD

**Issue by HSK077** [alecthw/openwrt-n1#1]
我见你描述写的是10.21.2.1，打不开页面准备放弃时用vi /etc/config/network看见地址是

旁路由：10.12.2.188
实际主路由地址：10.12.2.1
掩码：255.255.240.0

**Comment by alecthw** [comment]
> 我见你描述写的是10.21.2.1，打不开页面准备放弃时用vi /etc/config/network看见地址是
> 
> 旁路由：10.12.2.188 实际主路由地址：10.12.2.1 掩码：255.255.240.0

哈哈哈，昨天还在调，为了调的方便，还没改过去

**Comment by HSK077** [comment]
由于禁止DHCP，一知半解的试了好多遍都不对，最后用vi /etc/config/network才知道真实的地址。
我主路由地址使用10.1.1.1

**Comment by HSK077** [comment]
> 我见你描述写的是10.21.2.1，打不开页面准备放弃时用vi /etc/config/network看见地址是
> 
> 旁路由：10.12.2.188 实际主路由地址：10.12.2.1 掩码：255.255.240.0
